package com.aws.instance.budget.entity;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.aws.instance.budget.converter.FinancialYearsConverter;
import com.aws.instance.budget.vo.FinancialYear;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@DynamoDBTable(tableName = "person")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PersonEntity {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String middleName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBTypeConverted(converter = FinancialYearsConverter.class)
    @DynamoDBAttribute
    private List<FinancialYear> financialYears;
}
